package com.maxeydev.picklelog.ui.settings

object SettingsTestTags {
    const val SCREEN = "settings_screen"
    const val SCRIM = "settings_scrim"
    const val CLOSE = "settings_close"
    const val PRO_CARD = "settings_pro_card"
    const val PRO_STATUS = "settings_pro_status"
    const val SEE_PRO = "settings_see_pro"
    const val NAME_OPEN = "settings_name_open"
    const val NAME_FIELD = "settings_name_field"
    const val NAME_SAVE = "settings_name_save"
    const val DARK_THEME_TOGGLE = "settings_dark_theme_toggle"
    const val REMINDER_TOGGLE = "settings_reminder_toggle"
    const val REMINDER_TIME = "settings_reminder_time"
    const val REMINDER_BLOCKED = "settings_reminder_blocked"
    const val REMINDER_OPEN_SETTINGS = "settings_reminder_open_settings"
    const val BACKUP_MORE_INFO = "settings_backup_more_info"
    const val CLEAR_CACHE = "settings_clear_cache"
    const val CACHE_SIZE = "settings_cache_size"
    const val PRIVACY_OPEN = "settings_privacy_open"
    const val RATE_US = "settings_rate_us"
    const val ABOUT_OPEN = "settings_about_open"
    const val ERASE_OPEN = "settings_erase_open"
    const val ERASE_CONFIRM_FIELD = "settings_erase_confirm_field"
    const val ERASE_CONFIRM = "settings_erase_confirm"
    const val ERASE_EXPORT_FIRST = "settings_erase_export_first"
    const val ERASE_ERROR = "settings_erase_error"
}
